version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_AUTOPURGE_SNAP_RETAIN_COUNT: 3
      ZOO_AUTOPURGE_PURGE_INTERVAL: 1
      JUTE_MAXBUFFER: 20971520  # 20MB max. Nachrichtengröße
    networks:
      - kafka_network
    ports:
      - "2181:2181"

networks:
  kafka_network:
    driver: bridge
