version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_MAX_CLIENT_CNXNS: 60   # Erhöht die maximalen gleichzeitigen Verbindungen
      ZOO_AUTOPURGE_SNAP_RETAIN_COUNT: 3  # Snapshots reduzieren
      ZOO_AUTOPURGE_PURGE_INTERVAL: 1  # Auto-Purge für alte Snapshots
      JUTE_MAXBUFFER: 20971520  # 20MB max. Nachrichtengröße (statt 1MB)
    ports:
      - "2181:2181"
